apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app-deployment-frontend
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: poc-app-backend
        env:
          - name: REACT_APP_BACKEND_URL
            value: {{ .Values.backendServiceUrl }}
        image:  {{ .Values.image }}
        ports:
        - containerPort: 3000