apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32002